In [1]:
import torch 
import torch.nn as nn

In [2]:
GPT_CONFIG_124M = {
    "vocab_size" : 50257,
    "context_length" : 1024, 
    "emb_dim" : 768,
    "n_heads" : 12,
    "n_layers" : 12,
    "drop_rate" : 0.1,
    "qkv_bias" : False
}

In [3]:
from transformer import TransformerBlock 

x = torch.rand(2,4,768)
block = TransformerBlock(GPT_CONFIG_124M)
output = block(x)

print(output)

tensor([[[ 1.6046,  0.8208,  0.7661,  ...,  0.3137,  1.1557,  0.4213],
         [ 0.1289,  0.4490,  0.5705,  ..., -0.3779,  0.4342,  0.0148],
         [ 0.7680,  0.3040,  1.4052,  ..., -0.1587, -0.4956, -0.6078],
         [ 0.7276, -0.2249,  0.7353,  ...,  0.9519,  0.5780,  0.7664]],

        [[ 1.3445,  0.0173,  0.8077,  ...,  1.4564,  0.7403, -0.2304],
         [-0.1721, -0.2033,  0.1815,  ..., -0.6931,  1.1594, -0.3444],
         [ 1.0612,  0.3177,  0.6540,  ...,  0.0722,  0.1012, -0.7444],
         [-0.5824, -0.1383, -0.1491,  ...,  1.0233,  0.5363, -0.1270]]],
       grad_fn=<AddBackward0>)


In [4]:
import tiktoken
tokenizer = tiktoken.get_encoding("gpt2")
batch = []
txt1 = "Every effort moves you"
txt2 = "Every day holds a"
batch.append(torch.tensor(tokenizer.encode(txt1)))
batch.append(torch.tensor(tokenizer.encode(txt2)))
batch = torch.stack(batch, dim=0)
print(batch)

tensor([[6109, 3626, 6100,  345],
        [6109, 1110, 6622,  257]])


In [5]:
from mini_GPT import GPTModel

tokenizer = tiktoken.get_encoding("gpt2")
batch = []
txt1 = "Every effort moves you"
txt2 = "Every day holds a"
batch.append(torch.tensor(tokenizer.encode(txt1)))
batch.append(torch.tensor(tokenizer.encode(txt2)))
batch = torch.stack(batch, dim=0)
print(batch)

GPT2 = GPTModel(GPT_CONFIG_124M)
output = GPT2(batch)

print(output.shape)


total_parameters = sum(p.numel() for p in GPT2.parameters())

print(f"Total Parameters : {total_parameters}")


print(f"Embedding layer Shape : {GPT2.token_emb.weight.shape}")
print(f"Output layer Shape : {GPT2.out_head.weight.shape}")

tensor([[6109, 3626, 6100,  345],
        [6109, 1110, 6622,  257]])
torch.Size([2, 4, 50257])
Total Parameters : 163009536
Embedding layer Shape : torch.Size([50257, 768])
Output layer Shape : torch.Size([50257, 768])


In [8]:
from mini_GPT import GenerateText

start_context = " Hello, I am"
encoded = tokenizer.encode(start_context)

print('----------------------------------------------')
print(f"Text : {start_context}")
print(f"Encoded tokens : {encoded}")
encoder_tensor = torch.tensor(encoded).unsqueeze(0)

GPT2.eval()
out = GenerateText(model=GPT2, idx=encoder_tensor, max_new_tokens=6, context_size=GPT_CONFIG_124M["context_length"])
print(out)


decoded_text = tokenizer.decode(out.squeeze(0).tolist())
print(decoded_text)

----------------------------------------------
Text :  Hello, I am
Encoded tokens : [18435, 11, 314, 716]
tensor([[18435,    11,   314,   716, 29377, 28888, 44300,  5419, 34244, 32509]])
 Hello, I am BRE resentment 610 helps sensing":[{"
