In [1]:
import torch 
import torch.nn as nn

In [2]:
GPT_CONFIG_124M = {
    "vocab_size" : 50257,
    "context_length" : 1024, 
    "emb_dim" : 768,
    "n_heads" : 12,
    "n_layers" : 12,
    "drop_rate" : 0.1,
    "qkv_bias" : False
}

In [3]:
from transformer import TransformerBlock 

x = torch.rand(2,4,768)
block = TransformerBlock(GPT_CONFIG_124M)
output = block(x)

print(output)

tensor([[[ 1.4128,  0.3014,  0.2166,  ...,  0.4334,  1.2458,  1.4840],
         [ 0.7104, -0.4991, -0.0177,  ...,  0.4806, -0.0449,  0.6151],
         [ 0.4218,  0.7638, -0.0027,  ...,  0.3309, -0.2843,  1.6827],
         [ 0.7094,  0.0751,  0.6429,  ..., -0.3901,  0.4092,  0.5507]],

        [[ 0.6250,  0.5627,  0.2222,  ...,  0.7123,  0.6064,  0.8169],
         [ 0.5445,  1.0036,  0.9865,  ...,  1.1754, -0.3625,  1.2405],
         [ 0.1368,  0.5574,  1.2397,  ...,  1.0135,  1.4069,  1.6609],
         [ 0.5887,  0.4805,  0.8801,  ..., -0.2517,  0.6370,  0.6284]]],
       grad_fn=<AddBackward0>)


In [4]:
import tiktoken
tokenizer = tiktoken.get_encoding("gpt2")
batch = []
txt1 = "Every effort moves you"
txt2 = "Every day holds a"
batch.append(torch.tensor(tokenizer.encode(txt1)))
batch.append(torch.tensor(tokenizer.encode(txt2)))
batch = torch.stack(batch, dim=0)
print(batch)

tensor([[6109, 3626, 6100,  345],
        [6109, 1110, 6622,  257]])


In [5]:
from GPT import GPTModel

tokenizer = tiktoken.get_encoding("gpt2")
batch = []
txt1 = "Every effort moves you"
txt2 = "Every day holds a"
batch.append(torch.tensor(tokenizer.encode(txt1)))
batch.append(torch.tensor(tokenizer.encode(txt2)))
batch = torch.stack(batch, dim=0)
print(batch)

GPT2 = GPTModel(GPT_CONFIG_124M)
output = GPT2(batch)

print(output.shape)


total_parameters = sum(p.numel() for p in GPT2.parameters())

print(f"Total Parameters : {total_parameters}")


print(f"Embedding layer Shape : {GPT2.token_emb.weight.shape}")
print(f"Output layer Shape : {GPT2.out_head.weight.shape}")

tensor([[6109, 3626, 6100,  345],
        [6109, 1110, 6622,  257]])
torch.Size([2, 4, 50257])
Total Parameters : 163009536
Embedding layer Shape : torch.Size([50257, 768])
Output layer Shape : torch.Size([50257, 768])


In [7]:
from GPT import GenerateText

start_context = " Hello, I am"
encoded = tokenizer.encode(start_context)

print('----------------------------------------------')
print(f"Text : {start_context}")
print(f"Encoded tokens : {encoded}")
encoder_tensor = torch.tensor(encoded).unsqueeze(0)

GPT2.eval()
out = GenerateText(model=GPT2, idx=encoder_tensor, max_new_tokens=6, context_size=GPT_CONFIG_124M["context_length"])
print(out)


decoded_text = tokenizer.decode(out.squeeze(0).tolist())
print(decoded_text)

----------------------------------------------
Text :  Hello, I am
Encoded tokens : [18435, 11, 314, 716]
tensor([[18435,    11,   314,   716, 28776, 25763, 30601, 43332, 16676, 49932]])
 Hello, I amfashioned Duterte pluggedheterRememberrepair
